Przychodnia/Przychodnia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('cms/', admin.site.urls),
    path('przychodnia/', include('przychodnia_app.urls', namespace='przychodnia_app')),
    path('laboratorium/', include('laboratorium_app.urls', namespace='laboratorium_app')),
    path('', include('common.urls', namespace='common')),
]

Przychodnia/common/urls.py
from django.urls import path, include

from common import views

app_name = "common"

urlpatterns = [
    path(
        "login/",
        views.Login.as_view(),
        name="login"
    ),
    path(
        "logout/",
        views.Logout.as_view(),
        name="logout"
    ),
    path(
        "",
        views.RedirectToLoginPage.as_view(),
        name="homepage"
    ),
]

Przychodnia/przychodnia_app/urls.py
from django.urls import path, include

from przychodnia_app import views
from przychodnia_bad_fiz import views as bad_fiz_views
from przychodnia_pacjent import views as pacjent_views

app_name = "przychodnia_app"

urlpatterns = [
    ###################################################
    # Rejestratorka
    ###################################################
    path(
        "rejestratorka/wizyty-nowe",
        views.RejestratorkaWizytyNowe.as_view(),
        name="rejestratorka-wizyty-nowe"
    ),
    path(
        "rejestratorka/wizyty-stare",
        views.RejestratorkaWizytyStare.as_view(),
        name="rejestratorka-wizyty-stare"
    ),
    path(
        "rejestratorka/wizyty-anulowane",
        views.RejestratorkaAnulowaneWizyty.as_view(),
        name="rejestratorka-wizyty-anulowane"
    ),
    path(
        "rejestratorka/rejestruj-wizyte/",
        views.RejestratorkaWizytaDodaj.as_view(),
        name="rejestratorka-rejestruj-wizyte"
    ),
    path(
        "rejestratorka/dodaj-pacjenta/",
        views.RejestratorkaPacjentDodaj.as_view(),
        name="rejestratorka-dodaj-pacjenta"
    ),
    path(
        "rejestratorka/dodaj-adres/",
        views.RejestratorkaAdresDodaj.as_view(),
        name="rejestratorka-dodaj-adres"
    ),
    ###################################################
    # Lekarz
    ###################################################
    path(
        "lekarz/moje-wizyty",
        views.LekarzDashboard.as_view(),
        name="lekarz-moje-wizyty"
    ),
    path(
        "lekarz/moje-zakonczone-wizyty",
        views.LekarzZakonczoneWizyty.as_view(),
        name="lekarz-moje-zakonczone-wizyty"
    ),
    path(
        "lekarz/moje-anulowane-wizyty",
        views.LekarzAnulowaneWizyty.as_view(),
        name="lekarz-moje-anulowane-wizyty"
    ),
    path(
        "lekarz/wizyta/<int:wizyta_id>/realizuj/",
        views.LekarzRealizujWizyte.as_view(),
        name="lekarz-realizuj-wizyte"
    ),
    path(
        "lekarz/wizyta/<int:wizyta_id>/realizuj/inne-wizyty-pacjenta",
        views.LekarzPrzegladajInneWizyty.as_view(),
        name="przegladaj-inne-wizyty-pacjenta"
    ),
    path(
        "lekarz/wizyta/<int:wizyta_id>/realizuj/zlec-badanie-lab/",
        views.LekarzZlecBadanieLaboratoryjne.as_view(),
        name="lekarz-zlec-badanie-lab"
    ),
    path(
        "lekarz/wizyta/<int:wizyta_id>/realizuj/wykonaj-badanie-fiz/",
        views.LekarzWykonajBadanieFizykalne.as_view(),
        name="lekarz-wykonaj-badanie-fiz"
    ),
    ###################################################
    # Lekarz (Bad Fiz)
    ###################################################
    path(
        "lekarz/badanie-fiz/<int:pk>",
        bad_fiz_views.PrzychodniaBadFizDetail.as_view(),
        name="lekarz-bad-fiz-detail"
    ),
    ###################################################
    # Wspólne (przychodnia)
    ###################################################
    path(
        "anuluj-wizyte/<int:wizyta_id>/",
        views.PrzychodniaAnulujWizyte.as_view(),
        name="przychodnia-anuluj-wizyte"
    ),
    path(
        "pacjenci/",
        views.PrzychodniaPacjentLista.as_view(),
        name="przychodnia-pacjenci-list"
    ),
    path(
        "pacjent/<int:pk>/",
        pacjent_views.PacjentDetailView.as_view(),
        name="przychodnia-pacjent-detail"
    ),
    path(
        "pacjent/<int:pk>/badania",
        pacjent_views.PacjentBadaniaView.as_view(),
        name="przychodnia-pacjent-badania"
    ),
    path(
        "wizyta/<int:pk>/",
        views.PrzychodniaWizytaDetail.as_view(),
        name="przychodnia-wizyta-detail"
    ),
]

Przychodnia/przychodnia_app/models.py
from django.db import models

from common.models import User, CommonProfileModel


class Rejestratorka(CommonProfileModel):
    # Połączenie z głównym modelem użytkownika
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    role = models.CharField(max_length=16, default="REJESTRATORKA", editable=False)

    class Meta:
        verbose_name_plural = "Rejestratorki"

class Lekarz(CommonProfileModel):
    # Połączenie z głównym modelem użytkownika
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    role = models.CharField(max_length=16, default="LEKARZ", editable=False)
    npwz = models.CharField("NPWZ", max_length=7, unique=True)

    class Meta:
        verbose_name_plural = "Lekarze"

Przychodnia/przychodnia_pacjent/models.py
from django.db import models
from common.models import CommonProfileModel

class Adres(models.Model):
    miejscowosc = models.CharField("Miejscowość", max_length=32)
    ulica = models.CharField("Ulica", max_length=32)
    nr_domu = models.CharField("Numer domu", max_length=16)
    nr_lokalu = models.CharField("Numer Lokalu", max_length=16)

    def __str__(self):
        return "%s, %s %s/%s" % (self.miejscowosc, self.ulica, self.nr_domu, self.nr_lokalu)

    class Meta:
        verbose_name_plural = "Adresy Zamieszkania"


class Pacjent(CommonProfileModel):
    adres = models.ForeignKey(Adres, on_delete=models.PROTECT)
    pesel = models.CharField("PESEL", max_length=11, unique=True)

    def __str__(self):
        return "%s %s (%s)" % (self.imie, self.nazwisko, self.pesel)

    class Meta:
        verbose_name_plural = "Pacjenci"

Przychodnia/przychodnia_app/forms.py
from django import forms

from przychodnia_wizyta.models import Wizyta


class LekarzWywiadForm(forms.ModelForm):

    class Meta:
        model = Wizyta
        fields = ("opis", "diagnoza")

    def __init__(self, *args, **kwargs):
        super(LekarzWywiadForm, self).__init__(*args, **kwargs)
        self.fields['opis'].widget.attrs.update({
            'class': 'form-control',
            'rows': '4'
        })
        self.fields['diagnoza'].widget.attrs.update({
            'class': 'form-control',
            'rows': '4'
        })

Przychodnia/przychodnia_app/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponseRedirect
from django.views.generic import View
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.db.models import Q

from przychodnia_app.models import Rejestratorka
from przychodnia_wizyta.models import Wizyta
from przychodnia_pacjent.models import Pacjent

from przychodnia_wizyta.forms import WizytaForm
from przychodnia_pacjent.forms import PacjentForm
from przychodnia_pacjent.forms import AdresForm


class RejestratorkaWizytyNowe(View):
    template_name = "przychodnia_app/rejestratorka-wizyty-nowe.html"
    def get(self, request):
        context = {
            "nowe_wizyty": Wizyta.wizyty.get_new(),
        }
        return render(request, self.template_name, context)


class RejestratorkaWizytyStare(View):
    template_name = "przychodnia_app/rejestratorka-wizyty-stare.html"
    def get(self, request):
        context = {
            "stare_wizyty": Wizyta.wizyty.get_old(),
        }
        return render(request, self.template_name, context)


class LekarzDashboard(View):
    template_name = "przychodnia_app/lekarz-dashboard.html"
    def get(self, request):
        return render(request, self.template_name, {})


class WizytaCreate(CreateView):
    template_name = "przychodnia_app/wizyta-create.html"
    form_class = WizytaForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        rejestratorka = get_object_or_404(Rejestratorka, Q(user__id=self.request.user.id))
        self.object.rejestratorka = rejestratorka
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        messages.success(self.request, 'Wizyta zarejestrowana poprawnie')
        return reverse("przychodnia_app:rejestratorka-wizyty-nowe")


class PacjentCreate(CreateView):
    template_name = "przychodnia_app/pacjent-create.html"
    form_class = PacjentForm

    def get_success_url(self):
        messages.success(self.request, 'Pacjent dodany poprawnie')
        return reverse("przychodnia_app:rejestratorka-rejestruj-wizyte")

class PacjentRejestratorkaList(ListView):
    template_name = "przychodnia_app/pacjent-list-rejestratorka.html"
    model = Pacjent
    context_object_name = 'pacjenci'
    paginate_by = 50

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class AdresCreate(CreateView):
    template_name = "przychodnia_app/adres-create.html"
    form_class = AdresForm

    def get_success_url(self):
        messages.success(self.request, 'Adres dodany poprawnie')
        return reverse("przychodnia_app:rejestratorka-dodaj-pacjenta")

Przychodnia/przychodnia_app/views/views_lekarz.py
from django.shortcuts import render, redirect, reverse
from django.utils import timezone
from django.http import HttpResponseRedirect
from django.views.generic import View
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.db.models import Q

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from common.access_decorators_mixins import uprawniania_lekarz_wymagane

from przychodnia_wizyta.models import Wizyta
from przychodnia_app.forms import LekarzWywiadForm
from przychodnia_app.models import Lekarz
from laboratorium_app.models import BadanieLaboratoryjne
from przychodnia_bad_fiz.models import BadanieFizykalne
from laboratorium_app.forms import ZlecBadanieLaboratoryjneForm
from przychodnia_bad_fiz.forms import WykonajBadanieFizykalneForm


def lekarz_by_request(request):
    return Lekarz.objects.get(user=request.user)


@method_decorator(login_required(login_url='/login'), name='dispatch')
@method_decorator(uprawniania_lekarz_wymagane, name='dispatch')
class LekarzDashboard(View):
    template_name = "przychodnia_app/lekarz/moje-wizyty.html"
    def get(self, request):
        ja = lekarz_by_request(request)
        moje_wizyty = Wizyta.wizyty.filter_by_lekarz(ja, typ="REJ")
        moje_wizyty_count = moje_wizyty.count()
        return render(request, self.template_name, {
            "moje_wizyty": moje_wizyty,
            "moje_wizyty_count": moje_wizyty_count,
        })


@method_decorator(login_required(login_url='/login'), name='dispatch')
@method_decorator(uprawniania_lekarz_wymagane, name='dispatch')
class LekarzZakonczoneWizyty(View):
    template_name = "przychodnia_app/lekarz/moje-zakonczone-wizyty.html"
    def get(self, request):
        ja = lekarz_by_request(request)
        zakonczone_wizyty = Wizyta.wizyty.filter_by_lekarz(ja, typ="ZAK").order_by('-dt_zak_anul')
        return render(request, self.template_name, {
            "zakonczone_wizyty": zakonczone_wizyty
        })


@method_decorator(login_required(login_url='/login'), name='dispatch')
@method_decorator(uprawniania_lekarz_wymagane, name='dispatch')
class LekarzAnulowaneWizyty(View):
    template_name = "przychodnia_app/lekarz/moje-anulowane-wizyty.html"
    def get(self, request):
        ja = lekarz_by_request(request)
        anulowane_wizyty = Wizyta.wizyty.filter_by_lekarz(ja, typ="ANUL").order_by('-dt_zak_anul')
        return render(request, self.template_name, {
            "anulowane_wizyty": anulowane_wizyty
        })


@method_decorator(login_required(login_url='/login'), name='dispatch')
@method_decorator(uprawniania_lekarz_wymagane, name='dispatch')
class LekarzRealizujWizyte(View):
    template_name = "przychodnia_app/lekarz/realizuj-wizyte.html"
    def get(self, request, wizyta_id):
        realizowana_wizyta = get_object_or_404(Wizyta, id=wizyta_id, status="REJ")
        bad_lab_w_ramach_wizyty = BadanieLaboratoryjne.badania.w_ramach_wizyty(
            realizowana_wizyta
        )
        bad_fiz_w_ramach_wizyty = BadanieFizykalne.badania.w_ramach_wizyty(
            realizowana_wizyta
        )
        context = {
            "wywiad_form": LekarzWywiadForm(instance=realizowana_wizyta),
            "realizowana_wizyta": realizowana_wizyta,
            "bad_lab_w_ramach_wizyty": bad_lab_w_ramach_wizyty,
            "bad_fiz_w_ramach_wizyty": bad_fiz_w_ramach_wizyty,
        }
        return render(request, self.template_name, context)

    def post(self, request, wizyta_id):
        wizyta_id = self.kwargs.get('wizyta_id')
        wywiad_action = request.POST.get('wywiad_action')
        realizowana_wizyta = get_object_or_404(Wizyta, id=wizyta_id, status="REJ")
        form = LekarzWywiadForm(request.POST, instance=realizowana_wizyta)

        if wywiad_action == "zapisz":
            form.save()
            messages.success(self.request, "Zapisano stan wizyty")
            return HttpResponseRedirect(reverse(
                "przychodnia_app:lekarz-realizuj-wizyte",
                kwargs={
                "wizyta_id": wizyta_id
                }
            ))

        if wywiad_action == "zatwierdz":
            form.save()
            realizowana_wizyta.status = "ZAK"
            realizowana_wizyta.dt_zak_anul = timezone.now()
            realizowana_wizyta.save()
            messages.success(self.request, "Wizyta została zakończona")
            return HttpResponseRedirect(reverse(
                "przychodnia_app:lekarz-moje-wizyty"
            ))

        messages.success(self.request, "Coś poszło nie tak. Skontaktuj się z administratorem")
        return HttpResponseRedirect(reverse(
            "przychodnia_app:lekarz-realizuj-wizyte",
            kwargs={
            "wizyta_id": wizyta_id
            }
        ))

@method_decorator(login_required(login_url='/login'), name='dispatch')
@method_decorator(uprawniania_lekarz_wymagane, name='dispatch')
class LekarzPrzegladajInneWizyty(ListView):
    template_name = "przychodnia_app/lekarz/przegladaj-inne-wizyty.html"
    paginate_by = 20
    model = Wizyta
    context_object_name = "inne_wizyty_pacjenta"
    allow_empty = True

    def get(self, request, *args, **kwargs):
        realizowana_wizyta = get_object_or_404(
            self.model, id=kwargs["wizyta_id"]
        )
        self.object_list = self.get_queryset(realizowana_wizyta)
        context = self.get_context_data()
        context = {
            "realizowana_wizyta": realizowana_wizyta,
            **context,
        }
        return self.render_to_response(context)

    def get_queryset(self, realizowana_wizyta):
        return self.model.wizyty.inne_wizyty_pacjenta(
            realizowana_wizyta
        ).order_by("-dt_rej")


class BadanieView():
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        wizyta_id = self.kwargs["wizyta_id"]
        realizowana_wizyta = get_object_or_404(
            Wizyta, id=wizyta_id, status="REJ"
        )
        context = {
            "realizowana_wizyta": realizowana_wizyta,
            **context,
        }
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        wizyta = get_object_or_404(
            Wizyta, id=self.kwargs.get("wizyta_id")
        )
        self.object.wizyta = wizyta
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


@method_decorator(login_required(login_url='/login'), name='dispatch')
@method_decorator(uprawniania_lekarz_wymagane, name='dispatch')
class LekarzZlecBadanieLaboratoryjne(BadanieView, CreateView):
    template_name = "przychodnia_app/lekarz/zlec-badanie-lab.html"
    form_class = ZlecBadanieLaboratoryjneForm

    def get_success_url(self):
        messages.success(self.request, "Badanie laboratoryjne dodane poprawnie")
        return reverse(
            "przychodnia_app:lekarz-realizuj-wizyte",
            kwargs={
                "wizyta_id": self.kwargs.get("wizyta_id")
            }
        )


@method_decorator(login_required(login_url='/login'), name='dispatch')
@method_decorator(uprawniania_lekarz_wymagane, name='dispatch')
class LekarzWykonajBadanieFizykalne(BadanieView, CreateView):
    template_name = "przychodnia_app/lekarz/wykonaj-badanie-fiz.html"
    form_class = WykonajBadanieFizykalneForm

    def get_success_url(self):
        messages.success(self.request, "Badanie fizykalne dodane poprawnie")
        return reverse(
            "przychodnia_app:lekarz-realizuj-wizyte",
            kwargs={
                "wizyta_id": self.kwargs.get("wizyta_id")
            }
        )

Przychodnia/przychodnia_app/templates/przychodnia_app/adres-create.html
{% extends 'przychodnia_app/extend/base_rejestratorka.html' %}
{% block title %}Rejestruj wizyte{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-12 mt-3">
      <h4>Dodaj adres</h4>
      <hr>
      <form class="" action="{% url 'przychodnia_app:rejestratorka-dodaj-adres' %}" method="post">
        {% csrf_token %}
        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="id_miejscowosc">{{form.miejscowosc.label}}</label>
            {{form.miejscowosc}}
          </div>
          <div class="form-group col-md-6">
            <label for="id_ulica">{{form.ulica.label}}</label>
            {{form.ulica}}
          </div>
        </div>
        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="id_nr_domu">{{form.nr_domu.label}}</label>
            {{form.nr_domu}}
          </div>
          <div class="form-group col-md-6">
            <label for="id_nr_lokalu">{{form.nr_lokalu.label}}</label>
            {{form.nr_lokalu}}
          </div>
        </div>
        <hr>
        <input type="submit" name="submit" class="btn btn-primary" value="Dodaj adres">
      <form>
    </div>
  </div>
</div>
{% endblock %}

Przychodnia/przychodnia_app/templates/przychodnia_app/anuluj-wizyte.html
{% extends 'przychodnia_app/extend/base_przychodnia.html' %}
{% block title %}Stare wizyty{% endblock %}
{% block content %}

<h4 class="text-danger"><i class="fas fa-ban"></i>&nbsp;Anuluj wizyte (ID={{wizyta.pk}})</h4>

<p class="my-0">
  Umowiono na: <b>{{wizyta.dt_rej}}</b> przez <b>{{wizyta.rejestratorka}}</b>
</p>
<p class="my-0">
  Status:
  <b>
  {% if wizyta.status == "REJ" %}
  Zarejestrowana
    {% elif wizyta.status == "ZAK" %}
  Zakończona
    {% elif wizyta.status == "ANUL" %}
  Anulowana
  {% endif %}
  </b>
</p>

<div class="list-group flex-row mt-3">
  <a class="list-group-item border-0">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">Lekarz</h5>
    </div>
    <p class="mb-1">
      {{wizyta.lekarz.imie}} {{wizyta.lekarz.nazwisko}}
    </p>
    <small>NPWZ: {{wizyta.lekarz.npwz}}</small>
  </a>
  <a class="list-group-item border-0">
    <div class="d-flex w-100 justify-content-between">
      <h5 class="mb-1">Pacjent</h5>
    </div>
    <p class="mb-1">
      {{wizyta.pacjent.imie}} {{wizyta.pacjent.nazwisko}}
    </p>
    <small>
      {{wizyta.pacjent.pesel}}
    </small>
    <br>
    <small>
      {{wizyta.pacjent.adres}}
    </small>
  </a>
</div>


<form action="./" method="post">
  {% csrf_token %}
  <p>
    Czy na pewno chcesz anulować wizytę?
  </p>
  <button class="btn btn-danger" type="submit">Tak</button>
</form>

{% endblock %}

Przychodnia/przychodnia_app/templates/przychodnia_app/lekarz-dashboard.html
{% extends 'przychodnia_app/extend/base_lekarz.html' %}
{% block title %}Lekarz{% endblock %}
{% block content %}
lekarz
{% endblock %}

Przychodnia/przychodnia_app/templates/przychodnia_app/pacjent-create.html
{% extends 'przychodnia_app/extend/base_rejestratorka.html' %}
{% block title %}Rejestruj wizyte{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
    <div class="col-12 mt-3">
      <h4>Dodaj pacjenta</h4>
      <hr>
      <form class="" action="{% url 'przychodnia_app:rejestratorka-dodaj-pacjenta' %}" method="post">
        {% csrf_token %}

        <div class="form-row">
          <div class="form-group col-md-12">
            {{form.adres.label}}
            {{form.adres}}
            {{form.adres.errors}}
          </div>
        </div>
          <div class="col-md-12">

          <p>
            <a href="{% url 'przychodnia_app:rejestratorka-dodaj-adres' %}">
              <i class="fas fa-user-plus"></i>
              &nbsp;Wprowadź nowy adres
            </a>
          </p>

          </div>

        <div class="form-row">
          <div class="form-group col-md-12">
            {{form.pesel.label}}
            {{form.pesel}}
            {{form.pesel.errors}}
          </div>
        </div>

        <div class="form-row">
          <div class="form-group col-md-6">
            {{form.imie.label}}
            {{form.imie}}
            {{form.imie.errors}}
          </div>
          <div class="form-group col-md-6">
            {{form.nazwisko.label}}
            {{form.nazwisko}}
            {{form.nazwisko.errors}}
          </div>
        </div>

        <hr>
        <input type="submit" name="submit" class="btn btn-primary" value="Dodaj pacjenta">
      <form>
    </div>
  </div>
</div>
{% endblock %}

Przychodnia/przychodnia_app/templates/przychodnia_app/pacjent-lista.html
{% extends 'przychodnia_app/extend/base_przychodnia.html' %}
{% block title %}Pacjenci{% endblock %}
{% block content %}


<h4><i class="far fa-user"></i>&nbsp;Pacjenci</h4>
<a class="btn btn-primary btn-sm" href="{% url 'przychodnia_app:rejestratorka-dodaj-pacjenta' %}"><i class="fas fa-user-plus"></i>
  &nbsp;Wprowadź nowego pacjenta
</a>
{% include 'przychodnia_app/include/pagination.html' %}
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Imię i Nazwisko</th>
      <th scope="col">PESEL</th>
      <th scope="col">Adres</th>
    </tr>
  </thead>
  <tbody>
    {% for pacjent in pacjenci %}
    <tr>
      <td>
        <a href="{% url 'przychodnia_app:przychodnia-pacjent-detail' pk=pacjent.pk %}">
          {{pacjent.imie}} {{pacjent.nazwisko}}
        </a>
      </td>
      <td>{{pacjent.pesel}}</td>
      <td>{{pacjent.adres}}</td>
    </tr>
    {% empty %}
    <tr>
      <td colspan="3" class="text-center">
        -Brak-
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% include 'przychodnia_app/include/pagination.html' %}

{% endblock %}

Przychodnia/przychodnia_app/templates/przychodnia_app/rejestratorka-dashboard.html
{% extends 'przychodnia_app/extend/base_rejestratorka.html' %}
{% block title %}Rejestracja{% endblock %}
{% block content %}

<h4 class="mt-4">Nowe wizyty</h4>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Pacjent</th>
      <th scope="col">Lekarz</th>
      <th scope="col">Zarejestrowano</th>
      <th scope="col">Akcje</th>
    </tr>
  </thead>
  <tbody>
    {% for wizyta in nowe_wizyty %}
    <tr>
      <td>{{wizyta.pacjent}}</td>
      <td>{{wizyta.lekarz}}</td>
      <td>{{wizyta.dt_rej}}</td>
      <td>
        <a class="btn btn-primary" href="#" role="button" data-toggle="tooltip" data-placement="bottom" title="Pokaż szczegóły">
          <i class="far fa-eye"></i>
        </a>
        <a class="btn btn-danger" href="#" role="button" data-toggle="tooltip" data-placement="bottom" title="Anuluj wizyte">
          <i class="fas fa-ban"></i>
        </a>
      </td>
    </tr>
    {% empty %}
    <tr>
      <td colspan="4" class="text-center">
        -Brak-
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<h4>Stare wizyty</h4>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Pacjent</th>
      <th scope="col">Lekarz</th>
      <th scope="col">Zarejestrowano</th>
      <th scope="col">Akcje</th>
    </tr>
  </thead>
  <tbody>
    {% for wizyta in stare_wizyty %}
    <tr>
      <td>{{wizyta.pacjent}}</td>
      <td>{{wizyta.lekarz}}</td>
      <td>{{wizyta.dt_rej}}</td>
    </tr>
    {% empty %}
    <tr>
      <td colspan="4" class="text-center">
        -Brak-
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}

Przychodnia/przychodnia_app/templates/przychodnia_app/rejestratorka-wizyty-stare.html
{% extends 'przychodnia_app/extend/base_rejestratorka.html' %}
{% block title %}Rejestracja{% endblock %}
{% block content %}

<h4><i class="far fa-check-square"></i>&nbsp;Stare wizyty</h4>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Pacjent</th>
      <th scope="col">Lekarz</th>
      <th scope="col">Zarejestrowano</th>
      <th scope="col">Akcje</th>
    </tr>
  </thead>
  <tbody>
    {% for wizyta in stare_wizyty %}
    <tr>
      <td>{{wizyta.pacjent}}</td>
      <td>{{wizyta.lekarz}}</td>
      <td>{{wizyta.dt_rej}}</td>
    </tr>
    {% empty %}
    <tr>
      <td colspan="4" class="text-center">
        -Brak-
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}