Przychodnia/Przychodnia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('cms/', admin.site.urls),
    path('przychodnia/', include('przychodnia_app.urls', namespace='przychodnia_app')),
    path('laboratorium/', include('laboratorium_app.urls', namespace='laboratorium_app')),
    path('', include('common.urls', namespace='common')),
]

Przychodnia/common/urls.py
from django.urls import path, include

from common import views

app_name = "common"

urlpatterns = [
    path(
        "login/",
        views.Login.as_view(),
        name="login"
    ),
    path(
        "logout/",
        views.Logout.as_view(),
        name="logout"
    ),
    path(
        "",
        views.RedirectToLoginPage.as_view(),
        name="homepage"
    ),
]

Przychodnia/laboratorium_app/urls.py
from django.urls import path, include

from laboratorium_app import views

app_name = "laboratorium_app"

urlpatterns = [
    ###################################################
    # Laborant
    ###################################################
    path(
        "laborant/",
        views.LaborantDashboard.as_view(),
        name="laborant-dashboard"
    ),
    path(
        "laborant/wykonane-badania",
        views.LaborantWykonaneBadania.as_view(),
        name="laborant-wyk-badania"
    ),
    path(
        "laborant/anulowane-badania",
        views.LaborantAnulowaneBadania.as_view(),
        name="laborant-anul-badania"
    ),
    path(
        "laborant/wykonaj-badanie/<int:pk>/",
        views.LaborantWykAnulView.as_view(),
        name="laborant-wyk-anul"
    ),
    ###################################################
    # Kierownik Laboratorium
    ###################################################
    path(
        "kierownik-laboratorium/",
        views.KierownikLabDashboard.as_view(),
        name="kierownik-lab-dashboard"
    ),
    path(
        "kieronik-laboratorium/zatwierdz-badanie/<int:pk>/",
        views.KierownikZatwAnulView.as_view(),
        name="kierownik-zatw-anul"
    ),
    path(
        "badania-zatwierdzone/",
        views.KierownikZatwierdzoneBadania.as_view(),
        name="laboratorium-bad-lab-zatw-list"
    ),
    ###################################################
    # Badania
    ###################################################
    path(
        "badanie-lab/<int:pk>",
        views.LaboratoriumBadLabDetail.as_view(),
        name="laboratorium-bad-lab-detail"
    ),
]

Przychodnia/laboratorium_app/models.py
from django.db import models

from common.models import User, CommonProfileModel, SlownikBadan
from przychodnia_wizyta.models import Wizyta


class Laborant(CommonProfileModel):
    # Połączenie z głównym modelem użytkownika
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    role = models.CharField(max_length=16, default="LABORANT", editable=False)

    class Meta:
        verbose_name_plural = "Laboranci"

class KierownikLabarotorium(CommonProfileModel):
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    role = models.CharField(max_length=16, default="KIERLAB", editable=False)

    class Meta:
        verbose_name_plural = "Kierownicy Laboratorium"



class BadanieLaboratoryjneQuerySet(models.QuerySet):
    def w_ramach_wizyty(self, wizyta):
        return self.filter(
            wizyta=wizyta.id
        )


class BadanieLaboratoryjneManager(models.Manager):
    def get_queryset(self):
        return BadanieLaboratoryjneQuerySet(self.model, using=self._db)

    def w_ramach_wizyty(self, wizyta):
        return self.get_queryset().w_ramach_wizyty(wizyta)


class BadanieLaboratoryjne(models.Model):
    STATUS = (
        ("ZLE", "Zlecone"),
        ("WYK", "Wykonane"),
        ("ANUL_LAB", "Anulowane przez Laboranta"),
        ("ZATW", "Zatwierdzone"),
        ("ANUL_KLAB", "Anulowane przez Kier. Laboratorium"),
    )
    status = models.CharField(
        null=False, choices=STATUS, max_length=9, default="ZLE"
    )
    uwagi_lekarza = models.TextField(null=True, blank=True)
    dt_zlecenia = models.DateTimeField(auto_now_add=True)
    # TODO: Wynik w sensie pozytywny(true)/negatywny(false) BooleanField,
    #       czy jako TextField ?
    # wynik = models.BooleanField(default=False)
    wynik = models.TextField(blank=True)
    # Data wykonania/anulowania przez Laboranta
    dt_wyk_anul_lab = models.DateTimeField(null=True)
    # Data zatwierdzenia/anulowania przez Kier. Laboratorium
    dt_zatw_anul_klab = models.DateTimeField(null=True)
    uwagi_kierownika = models.TextField(null=True, blank=True)
    slownik = models.ForeignKey(SlownikBadan, on_delete=models.PROTECT)
    wizyta = models.ForeignKey(Wizyta, on_delete=models.PROTECT)

    laborant = models.ForeignKey(
        Laborant, null=True, blank=True, on_delete=models.PROTECT
    )
    kier_lab = models.ForeignKey(
        KierownikLabarotorium, null=True, blank=True, on_delete=models.PROTECT
    )

    badania = BadanieLaboratoryjneManager()

    class Meta:
        verbose_name_plural = "Badania Laboratoryjne"

Przychodnia/laboratorium_app/forms.py
from django import forms

from laboratorium_app.models import BadanieLaboratoryjne
from common.models import SlownikBadan


class ZlecBadanieLaboratoryjneForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['uwagi_lekarza'].widget.attrs.update({
            'class': 'form-control'
        })
        self.fields['slownik'].widget.attrs.update({
            'class': 'form-control select2-select'
        })
        self.fields['slownik'].queryset = SlownikBadan.objects.filter(typ="L")

    class Meta:
        model = BadanieLaboratoryjne
        fields = ("uwagi_lekarza", "slownik")


class BadanieLabWykonaj(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['wynik'].widget.attrs.update({
            'class': 'form-control'
        })

    class Meta:
        model = BadanieLaboratoryjne
        fields = ("wynik",)


class BadanieKierZatwierdz(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['uwagi_kierownika'].widget.attrs.update({
            'class': 'form-control'
        })

    class Meta:
        model = BadanieLaboratoryjne
        fields = ("uwagi_kierownika",)

Przychodnia/laboratorium_app/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.views.generic.list import ListView
from django.utils import timezone
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.utils.decorators import method_decorator
from django.views.generic.detail import DetailView
from common.access_decorators_mixins import (
    uprawniania_laborant_wymagane,
    uprawniania_kierownik_lab_wymagane,
    uprawniania_przegladanie_badan_wymagane
)
from laboratorium_app.models import BadanieLaboratoryjne, Laborant, KierownikLabarotorium
from django.views.generic import View
from laboratorium_app.forms import BadanieLabWykonaj, BadanieKierZatwierdz


def laborant_by_request(request):
    return Laborant.objects.get(user=request.user)

def kier_lab_by_request(request):
    return KierownikLabarotorium.objects.get(user=request.user)


@method_decorator(login_required(login_url='/login'), name='dispatch')
@method_decorator(uprawniania_przegladanie_badan_wymagane, name='dispatch')
class LaboratoriumBadLabDetail(DetailView):
    template_name = "laboratorium_app/bad-lab-detail.html"
    context_object_name = "badanie_lab"
    model = BadanieLaboratoryjne

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


@method_decorator(login_required(login_url='/login'), name='dispatch')
@method_decorator(uprawniania_laborant_wymagane, name='dispatch')
class LaborantDashboard(View):
    template_name = "laboratorium_app/laborant-dashboard.html"
    def get(self, request):
        context = {}
        context["badania"] = BadanieLaboratoryjne.badania.filter(status="ZLE").order_by("-dt_zlecenia")
        return render(request, self.template_name, context)


@method_decorator(login_required(login_url='/login'), name='dispatch')
@method_decorator(uprawniania_kierownik_lab_wymagane, name='dispatch')
class KierownikLabDashboard(ListView):
    template_name = "laboratorium_app/kierownik-lab-dashboard.html"
    paginate_by = 20
    model = BadanieLaboratoryjne
    context_object_name = "wyk_badania"
    allow_empty = True

    def get_queryset(self):
        return self.model.badania.filter(status="WYK").order_by("-dt_wyk_anul_lab")


@method_decorator(login_required(login_url='/login'), name='dispatch')
@method_decorator(uprawniania_przegladanie_badan_wymagane, name='dispatch')
class LaborantWykonaneBadania(ListView):
    template_name = "laboratorium_app/laborant-wyk-badania.html"
    paginate_by = 20
    model = BadanieLaboratoryjne
    context_object_name = "wyk_badania"
    allow_empty = True

    def get_queryset(self):
        return self.model.badania.filter(status="WYK").order_by("-dt_wyk_anul_lab")

@method_decorator(login_required(login_url='/login'), name='dispatch')
@method_decorator(uprawniania_przegladanie_badan_wymagane, name='dispatch')
class LaborantAnulowaneBadania(ListView):
    template_name = "laboratorium_app/laborant-anul-badania.html"
    paginate_by = 20
    model = BadanieLaboratoryjne
    context_object_name = "anul_badania"
    allow_empty = True

    def get_queryset(self):
        return self.model.badania.filter(
            Q(status="ANUL_LAB") | Q(status="ANUL_KLAB")
        ).order_by("-dt_wyk_anul_lab")


@method_decorator(login_required(login_url='/login'), name='dispatch')
@method_decorator(uprawniania_laborant_wymagane, name='dispatch')
class LaborantWykAnulView(DetailView):
    template_name = "laboratorium_app/laborant-wyk-anul.html"
    context_object_name = "badania"
    model = BadanieLaboratoryjne

    def post(self, request, **kwargs):
        ja = laborant_by_request(request)
        badanie = get_object_or_404(BadanieLaboratoryjne, id=kwargs.get("pk"))
        wynik = request.POST.get("wynik")
        bad_wyk_action = request.POST.get("bad_wyk_action")
        bad_anul_action = request.POST.get("bad_anul_action")

        if bad_wyk_action:
            messages.success(self.request, "Wykonano badanie laboratoryjne")
            badanie.wynik = wynik
            badanie.status = "WYK"
            badanie.dt_wyk_anul_lab = timezone.now()
            badanie.laborant = ja
            badanie.save()

        if bad_anul_action:
            messages.success(self.request, "Anulowano badanie laboratoryjne")
            badanie.wynik = wynik
            badanie.status = "ANUL_LAB"
            badanie.dt_wyk_anul_lab = timezone.now()
            badanie.laborant = ja
            badanie.save()

        return redirect(reverse("laboratorium_app:laborant-dashboard"))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = BadanieLabWykonaj(instance=kwargs.get("object"))
        return context


@method_decorator(login_required(login_url='/login'), name='dispatch')
@method_decorator(uprawniania_kierownik_lab_wymagane, name='dispatch')
class KierownikZatwAnulView(DetailView):
    template_name = "laboratorium_app/kierownik-zatw-anul.html"
    context_object_name = "badania"
    model = BadanieLaboratoryjne

    def post(self, request, **kwargs):
        ja = kier_lab_by_request(request)
        badanie = get_object_or_404(BadanieLaboratoryjne, id=kwargs.get("pk"))
        uwagi_kierownika = request.POST.get("uwagi_kierownika")
        bad_wyk_action = request.POST.get("bad_zatw_action")
        bad_anul_action = request.POST.get("bad_anul_action")

        if bad_wyk_action:
            messages.success(self.request, "Zatwierdzono badanie laboratoryjne")
            badanie.uwagi_kierownika = uwagi_kierownika
            badanie.status = "ZATW"
            badanie.dt_zatw_anul_klab = timezone.now()
            badanie.kier_lab = ja
            badanie.save()

        if bad_anul_action:
            messages.success(self.request, "Anulowano badanie laboratoryjne")
            badanie.uwagi_kierownika = uwagi_kierownika
            badanie.status = "ANUL_KLAB"
            badanie.dt_zatw_anul_klab = timezone.now()
            badanie.kier_lab = ja
            badanie.save()

        return redirect(reverse("laboratorium_app:kierownik-lab-dashboard"))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = BadanieKierZatwierdz(instance=kwargs.get("object"))
        return context


@method_decorator(login_required(login_url='/login'), name='dispatch')
@method_decorator(uprawniania_przegladanie_badan_wymagane, name='dispatch')
class KierownikZatwierdzoneBadania(ListView):
    template_name = "laboratorium_app/badania-zatw.html"
    paginate_by = 20
    model = BadanieLaboratoryjne
    context_object_name = "zatw_badania"
    allow_empty = True

    def get_queryset(self):
        return self.model.badania.filter(status="ZATW").order_by("-dt_zatw_anul_klab")

Przychodnia/laboratorium_app/templates/laboratorium_app/bad-lab-detail.html
{% extends 'przychodnia_app/extend/base_przychodnia.html' %}
{% block title %}Wizyta - szczegóły{% endblock %}
{% block content %}

<h4>
  Szczegóły badanie laboratoryjnego (ID={{object.pk}}) <br>
  <small>({{object.slownik.key}}) {{object.slownik.nazwa}}</small>
</h4>
<p class="p-0 m-0">
  Lekarz: {{object.wizyta.lekarz}} ({{object.wizyta.lekarz.npwz}})
</p>
<p class="p-0 m-0">
  Pacjent: {{object.wizyta.pacjent.imie}} {{object.wizyta.pacjent.nazwisko}}
</p>
<p class="p-0 m-0">
  Data zlecenia: {{object.dt_zlecenia}}
</p>
<p class="p-0 m-0">
  Status:
  <b>
    {% include 'laboratorium_app/include/badanie_lab_status_text.html' with badanie_lab=object %}
  </b>
</p>
<p class="p-0 m-0">
  {% if object.status == "ANUL_LAB" %}
  Data anulowania: {{object.dt_wyk_anul_lab}}
  {% endif %}
  {% if object.status == "ANUL_KLAB" %}
  Data anulowania: {{object.dt_zatw_anul_klab}}
  {% endif %}
</p>

<p class="p-0 m-0">
  {% if object.status == "WYK" %}
  Data wykonania: {{object.dt_wyk_anul_lab}}
  {% endif %}
  {% if object.status == "ZATW" %}
  Data zatwierdzenia: {{object.dt_zatw_anul_klab}}
  {% endif %}
</p>
{% if object.status == "ZATW" %}
<p class="p-0 m-0">
  Wykonane przez: {{object.laborant}}
</p>
<p class="p-0 m-0">
  Data wykonania: {{object.dt_wyk_anul_lab}}
</p>
{% endif %}

<br>
<b>Uwagi lekarza</b>
<p>
  {% if object.uwagi_lekarza %}
  {{object.uwagi_lekarza}}
  {% else %}
  -Brak-
  {% endif %}
</p>
{% if object.wynik %}
<b>Wynik</b>
<p>
  {{object.wynik}}
</p>
<b>Uwagi kierownika laboratorium</b>
<p>
  {% if object.uwagi_kierownika %}
  {{object.uwagi_kierownika}}
  {% else %}
  -Brak-
  {% endif %}
</p>
{% endif %}

{% endblock %}

Przychodnia/laboratorium_app/templates/laboratorium_app/badania-zatw.html
{% extends 'przychodnia_app/extend/base_przychodnia.html' %}
{% block title %}Laborant{% endblock %}
{% block content %}

<h4>
  <i class="fas fas fa-vial"></i>&nbsp;Wykonane badania laboratoryjne
</h4>
{% include 'przychodnia_app/include/pagination.html' %}
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Zatwierdzono</th>
      <th scope="col">Nazwa badania</th>
      <th scope="col">Status</th>
      <th scope="col">Akcje</th>
    </tr>
  </thead>
  <tbody>
    {% for bad_lab in zatw_badania %}
    <tr>
      <td>
        {{bad_lab.dt_zatw_anul_klab}}
      </td>
      <td>
        <span data-toggle="tooltip" data-placement="right" title="{{bad_lab.slownik.key}}">
          {{bad_lab.slownik.nazwa}}
        </span>
      </td>
      <td>
        {% include 'laboratorium_app/include/badanie_lab_status_text.html' with badanie_lab=bad_lab %}
      </td>
      <td>
        <a href="{% url 'laboratorium_app:laboratorium-bad-lab-detail' pk=bad_lab.pk %}" class="btn btn-sm btn-primary" href="#" role="button" data-toggle="tooltip" data-placement="bottom" title="Pokaż szczegóły badania">
          <i class="far fa-eye"></i>
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% include 'przychodnia_app/include/pagination.html' %}
{% endblock %}

Przychodnia/laboratorium_app/templates/laboratorium_app/kierownik-lab-dashboard.html
{% extends 'przychodnia_app/extend/base_przychodnia.html' %}
{% block title %}Laborant{% endblock %}
{% block content %}

<h4>
  <i class="fas fas fa-vial"></i>&nbsp;Wykonane badania laboratoryjne
</h4>
{% include 'przychodnia_app/include/pagination.html' %}
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Nazwa badania</th>
      <th scope="col">Status</th>
      <th scope="col">Akcje</th>
    </tr>
  </thead>
  <tbody>
    {% for bad_lab in wyk_badania %}
    <tr>
      <td>
        <span data-toggle="tooltip" data-placement="right" title="{{bad_lab.slownik.key}}">
          {{bad_lab.slownik.nazwa}}
        </span>
      </td>
      <td>
        {% include 'laboratorium_app/include/badanie_lab_status_text.html' with badanie_lab=bad_lab %}
      </td>
      <td>
        <a class="btn btn-sm btn-success" href="{% url 'laboratorium_app:kierownik-zatw-anul' pk=bad_lab.pk %}" role="button" data-toggle="tooltip" data-placement="bottom" title="Zatwierdź badanie laboratoryjne">
          <i class="far fa-check-square"></i>
        </a>
        <a href="{% url 'laboratorium_app:laboratorium-bad-lab-detail' pk=bad_lab.pk %}" class="btn btn-sm btn-primary" href="#" role="button" data-toggle="tooltip" data-placement="bottom" title="Pokaż szczegóły badania">
          <i class="far fa-eye"></i>
        </a>
      </td>
    </tr>
    {% empty %}
    <tr>
      <td colspan="3" class="text-center">-Brak-</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% include 'przychodnia_app/include/pagination.html' %}
{% endblock %}

Przychodnia/laboratorium_app/templates/laboratorium_app/kierownik-zatw-anul.html
{% extends 'przychodnia_app/extend/base_przychodnia.html' %}
{% block title %}Laborant{% endblock %}
{% block content %}

<h4>
  <i class="fas fa-vial"></i>
  &nbsp;Zatwierdź/Anuluj badanie laboratoryjne
</h4>

<h4>
  ({{object.slownik.key}}) {{object.slownik.nazwa}}
</h4>
<p class="m-0 p-0">
  Wykonano przez <b>{{object.laborant}}</b> dnia <b>{{object.dt_wyk_anul_lab}}</b>
</p>
<p class="m-0 p-0">
  Lekarz zlecający: {{object.wizyta.lekarz}}
</p>
<p class="m-0 p-0">
  Data zlecenia: {{object.dt_zlecenia}}
</p>
<p class="m-0 p-0">
  Uwagi lekarza:
</p>
<code>
  {{object.uwagi_lekarza}}
</code>
<p class="m-0 p-0">
  Wynik badania:
</p>
<code>
  {{object.wynik}}
</code>
<hr>
<form class="" action="." method="post">
  {% csrf_token %}
  {{form}}
  <hr>
  <input type="submit" class="btn btn-sm btn-success" name="bad_zatw_action" value="Zatwierdź badanie">
  <input type="submit" class="btn btn-sm btn-danger" name="bad_anul_action" value="Anuluj badanie">
</form>


{% endblock %}

Przychodnia/laboratorium_app/templates/laboratorium_app/laborant-anul-badania.html
{% extends 'przychodnia_app/extend/base_przychodnia.html' %}
{% block title %}Laborant{% endblock %}
{% block content %}

<h4>
  <i class="fas fas fa-vial"></i>&nbsp;Anulowane badania laboratoryjne
</h4>
{% include 'przychodnia_app/include/pagination.html' %}
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Anulowano</th>
      <th scope="col">Nazwa badania</th>
      <th scope="col">Status</th>
      <th scope="col">Akcje</th>
    </tr>
  </thead>
  <tbody>
    {% for bad_lab in anul_badania %}
    <tr>
      <td>
        {{bad_lab.dt_wyk_anul_lab}}
      </td>
      <td>
        <span data-toggle="tooltip" data-placement="right" title="{{bad_lab.slownik.key}}">
          {{bad_lab.slownik.nazwa}}
        </span>
      </td>
      <td>
        {% include 'laboratorium_app/include/badanie_lab_status_text.html' with badanie_lab=bad_lab %}
      </td>
      <td>
        <a href="{% url 'laboratorium_app:laboratorium-bad-lab-detail' pk=bad_lab.pk %}" class="btn btn-sm btn-primary" href="#" role="button" data-toggle="tooltip" data-placement="bottom" title="Pokaż szczegóły badania">
          <i class="far fa-eye"></i>
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% include 'przychodnia_app/include/pagination.html' %}

{% endblock %}

Przychodnia/laboratorium_app/templates/laboratorium_app/laborant-dashboard.html
{% extends 'przychodnia_app/extend/base_przychodnia.html' %}
{% block title %}Laborant{% endblock %}
{% block content %}

<h4>
  <i class="fas fas fa-vial"></i>&nbsp;Badania laboratoryjne
</h4>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Zlecono</th>
      <th scope="col">Nazwa badania</th>
      <th scope="col">Status</th>
      <th scope="col">Akcje</th>
    </tr>
  </thead>
  <tbody>
    {% for bad_lab in badania %}
    <tr>
      <td>
        {{bad_lab.dt_zlecenia}}
      </td>
      <td>
        <span data-toggle="tooltip" data-placement="right" title="{{bad_lab.slownik.key}}">
          {{bad_lab.slownik.nazwa}}
        </span>
      </td>
      <td>
        {% include 'laboratorium_app/include/badanie_lab_status_text.html' with badanie_lab=bad_lab %}
      </td>
      <td>
        <a class="btn btn-sm btn-success" href="{% url 'laboratorium_app:laborant-wyk-anul' pk=bad_lab.pk %}" role="button" data-toggle="tooltip" data-placement="bottom" title="Wykonaj badanie laboratoryjne">
          <i class="fas fa-vial"></i>
        </a>
        <a href="{% url 'laboratorium_app:laboratorium-bad-lab-detail' pk=bad_lab.pk %}" class="btn btn-sm btn-primary" href="#" role="button" data-toggle="tooltip" data-placement="bottom" title="Pokaż szczegóły badania">
          <i class="far fa-eye"></i>
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>


{% endblock %}

Przychodnia/laboratorium_app/templates/laboratorium_app/laborant-wyk-anul.html
{% extends 'przychodnia_app/extend/base_przychodnia.html' %}
{% block title %}Laborant{% endblock %}
{% block content %}

<h4>
  ({{object.slownik.key}}) {{object.slownik.nazwa}}
</h4>

<form class="" action="." method="post">
  {% csrf_token %}
  {{form}}
  <hr>
  <input type="submit" class="btn btn-sm btn-success" name="bad_wyk_action" value="Wykonaj badanie">
  <input type="submit" class="btn btn-sm btn-danger" name="bad_anul_action" value="Anuluj badanie">
</form>


{% endblock %}

Przychodnia/laboratorium_app/templates/laboratorium_app/laborant-wyk-badania.html
{% extends 'przychodnia_app/extend/base_przychodnia.html' %}
{% block title %}Laborant{% endblock %}
{% block content %}

<h4>
  <i class="fas fas fa-vial"></i>&nbsp;Wykonane badania laboratoryjne
</h4>
{% include 'przychodnia_app/include/pagination.html' %}
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Wykonano</th>
      <th scope="col">Nazwa badania</th>
      <th scope="col">Status</th>
      <th scope="col">Akcje</th>
    </tr>
  </thead>
  <tbody>
    {% for bad_lab in wyk_badania %}
    <tr>
      <td>
        {{bad_lab.dt_wyk_anul_lab}}
      </td>
      <td>
        <span data-toggle="tooltip" data-placement="right" title="{{bad_lab.slownik.key}}">
          {{bad_lab.slownik.nazwa}}
        </span>
      </td>
      <td>
        {% include 'laboratorium_app/include/badanie_lab_status_text.html' with badanie_lab=bad_lab %}
      </td>
      <td>
        <a href="{% url 'laboratorium_app:laboratorium-bad-lab-detail' pk=bad_lab.pk %}" class="btn btn-sm btn-primary" href="#" role="button" data-toggle="tooltip" data-placement="bottom" title="Pokaż szczegóły badania">
          <i class="far fa-eye"></i>
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% include 'przychodnia_app/include/pagination.html' %}
{% endblock %}