Przychodnia/Przychodnia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('cms/', admin.site.urls),
    path('przychodnia/', include('przychodnia_app.urls', namespace='przychodnia_app')),
    path('laboratorium/', include('laboratorium_app.urls', namespace='laboratorium_app')),
    path('', include('common.urls', namespace='common')),
]

Przychodnia/common/urls.py
from django.urls import path, include

from common import views

app_name = "common"

urlpatterns = [
    path(
        "login/",
        views.Login.as_view(),
        name="login"
    ),
    path(
        "logout/",
        views.Logout.as_view(),
        name="logout"
    ),
    path(
        "",
        views.RedirectToLoginPage.as_view(),
        name="homepage"
    ),
]

Przychodnia/przychodnia_app/urls.py
from django.urls import path, include

from przychodnia_app import views
from przychodnia_bad_fiz import views as bad_fiz_views
from przychodnia_pacjent import views as pacjent_views

app_name = "przychodnia_app"

urlpatterns = [
    ###################################################
    # Rejestratorka
    ###################################################
    path(
        "rejestratorka/wizyty-nowe",
        views.RejestratorkaWizytyNowe.as_view(),
        name="rejestratorka-wizyty-nowe"
    ),
    path(
        "rejestratorka/wizyty-stare",
        views.RejestratorkaWizytyStare.as_view(),
        name="rejestratorka-wizyty-stare"
    ),
    path(
        "rejestratorka/wizyty-anulowane",
        views.RejestratorkaAnulowaneWizyty.as_view(),
        name="rejestratorka-wizyty-anulowane"
    ),
    path(
        "rejestratorka/rejestruj-wizyte/",
        views.RejestratorkaWizytaDodaj.as_view(),
        name="rejestratorka-rejestruj-wizyte"
    ),
    path(
        "rejestratorka/dodaj-pacjenta/",
        views.RejestratorkaPacjentDodaj.as_view(),
        name="rejestratorka-dodaj-pacjenta"
    ),
    path(
        "rejestratorka/dodaj-adres/",
        views.RejestratorkaAdresDodaj.as_view(),
        name="rejestratorka-dodaj-adres"
    ),
    ###################################################
    # Lekarz
    ###################################################
    path(
        "lekarz/moje-wizyty",
        views.LekarzDashboard.as_view(),
        name="lekarz-moje-wizyty"
    ),
    path(
        "lekarz/moje-zakonczone-wizyty",
        views.LekarzZakonczoneWizyty.as_view(),
        name="lekarz-moje-zakonczone-wizyty"
    ),
    path(
        "lekarz/moje-anulowane-wizyty",
        views.LekarzAnulowaneWizyty.as_view(),
        name="lekarz-moje-anulowane-wizyty"
    ),
    path(
        "lekarz/wizyta/<int:wizyta_id>/realizuj/",
        views.LekarzRealizujWizyte.as_view(),
        name="lekarz-realizuj-wizyte"
    ),
    path(
        "lekarz/wizyta/<int:wizyta_id>/realizuj/inne-wizyty-pacjenta",
        views.LekarzPrzegladajInneWizyty.as_view(),
        name="przegladaj-inne-wizyty-pacjenta"
    ),
    path(
        "lekarz/wizyta/<int:wizyta_id>/realizuj/zlec-badanie-lab/",
        views.LekarzZlecBadanieLaboratoryjne.as_view(),
        name="lekarz-zlec-badanie-lab"
    ),
    path(
        "lekarz/wizyta/<int:wizyta_id>/realizuj/wykonaj-badanie-fiz/",
        views.LekarzWykonajBadanieFizykalne.as_view(),
        name="lekarz-wykonaj-badanie-fiz"
    ),
    ###################################################
    # Lekarz (Bad Fiz)
    ###################################################
    path(
        "lekarz/badanie-fiz/<int:pk>",
        bad_fiz_views.PrzychodniaBadFizDetail.as_view(),
        name="lekarz-bad-fiz-detail"
    ),
    ###################################################
    # Wspólne (przychodnia)
    ###################################################
    path(
        "anuluj-wizyte/<int:wizyta_id>/",
        views.PrzychodniaAnulujWizyte.as_view(),
        name="przychodnia-anuluj-wizyte"
    ),
    path(
        "pacjenci/",
        views.PrzychodniaPacjentLista.as_view(),
        name="przychodnia-pacjenci-list"
    ),
    path(
        "pacjent/<int:pk>/",
        pacjent_views.PacjentDetailView.as_view(),
        name="przychodnia-pacjent-detail"
    ),
    path(
        "pacjent/<int:pk>/badania",
        pacjent_views.PacjentBadaniaView.as_view(),
        name="przychodnia-pacjent-badania"
    ),
    path(
        "wizyta/<int:pk>/",
        views.PrzychodniaWizytaDetail.as_view(),
        name="przychodnia-wizyta-detail"
    ),
]

Przychodnia/przychodnia_app/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponseRedirect
from django.views.generic import View
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.db.models import Q

from przychodnia_app.models import Rejestratorka
from przychodnia_wizyta.models import Wizyta
from przychodnia_pacjent.models import Pacjent

from przychodnia_wizyta.forms import WizytaForm
from przychodnia_pacjent.forms import PacjentForm
from przychodnia_pacjent.forms import AdresForm


class RejestratorkaWizytyNowe(View):
    template_name = "przychodnia_app/rejestratorka-wizyty-nowe.html"
    def get(self, request):
        context = {
            "nowe_wizyty": Wizyta.wizyty.get_new(),
        }
        return render(request, self.template_name, context)


class RejestratorkaWizytyStare(View):
    template_name = "przychodnia_app/rejestratorka-wizyty-stare.html"
    def get(self, request):
        context = {
            "stare_wizyty": Wizyta.wizyty.get_old(),
        }
        return render(request, self.template_name, context)


class LekarzDashboard(View):
    template_name = "przychodnia_app/lekarz-dashboard.html"
    def get(self, request):
        return render(request, self.template_name, {})


class WizytaCreate(CreateView):
    template_name = "przychodnia_app/wizyta-create.html"
    form_class = WizytaForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        rejestratorka = get_object_or_404(Rejestratorka, Q(user__id=self.request.user.id))
        self.object.rejestratorka = rejestratorka
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        messages.success(self.request, 'Wizyta zarejestrowana poprawnie')
        return reverse("przychodnia_app:rejestratorka-wizyty-nowe")


class PacjentCreate(CreateView):
    template_name = "przychodnia_app/pacjent-create.html"
    form_class = PacjentForm

    def get_success_url(self):
        messages.success(self.request, 'Pacjent dodany poprawnie')
        return reverse("przychodnia_app:rejestratorka-rejestruj-wizyte")

class PacjentRejestratorkaList(ListView):
    template_name = "przychodnia_app/pacjent-list-rejestratorka.html"
    model = Pacjent
    context_object_name = 'pacjenci'
    paginate_by = 50

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class AdresCreate(CreateView):
    template_name = "przychodnia_app/adres-create.html"
    form_class = AdresForm

    def get_success_url(self):
        messages.success(self.request, 'Adres dodany poprawnie')
        return reverse("przychodnia_app:rejestratorka-dodaj-pacjenta")

Przychodnia/przychodnia_app/views/views_lekarz.py
from django.shortcuts import render, redirect, reverse
from django.utils import timezone
from django.http import HttpResponseRedirect
from django.views.generic import View
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.db.models import Q

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from common.access_decorators_mixins import uprawniania_lekarz_wymagane

from przychodnia_wizyta.models import Wizyta
from przychodnia_app.forms import LekarzWywiadForm
from przychodnia_app.models import Lekarz
from laboratorium_app.models import BadanieLaboratoryjne
from przychodnia_bad_fiz.models import BadanieFizykalne
from laboratorium_app.forms import ZlecBadanieLaboratoryjneForm
from przychodnia_bad_fiz.forms import WykonajBadanieFizykalneForm


def lekarz_by_request(request):
    return Lekarz.objects.get(user=request.user)


@method_decorator(login_required(login_url='/login'), name='dispatch')
@method_decorator(uprawniania_lekarz_wymagane, name='dispatch')
class LekarzDashboard(View):
    template_name = "przychodnia_app/lekarz/moje-wizyty.html"
    def get(self, request):
        ja = lekarz_by_request(request)
        moje_wizyty = Wizyta.wizyty.filter_by_lekarz(ja, typ="REJ")
        moje_wizyty_count = moje_wizyty.count()
        return render(request, self.template_name, {
            "moje_wizyty": moje_wizyty,
            "moje_wizyty_count": moje_wizyty_count,
        })


@method_decorator(login_required(login_url='/login'), name='dispatch')
@method_decorator(uprawniania_lekarz_wymagane, name='dispatch')
class LekarzZakonczoneWizyty(View):
    template_name = "przychodnia_app/lekarz/moje-zakonczone-wizyty.html"
    def get(self, request):
        ja = lekarz_by_request(request)
        zakonczone_wizyty = Wizyta.wizyty.filter_by_lekarz(ja, typ="ZAK").order_by('-dt_zak_anul')
        return render(request, self.template_name, {
            "zakonczone_wizyty": zakonczone_wizyty
        })


@method_decorator(login_required(login_url='/login'), name='dispatch')
@method_decorator(uprawniania_lekarz_wymagane, name='dispatch')
class LekarzAnulowaneWizyty(View):
    template_name = "przychodnia_app/lekarz/moje-anulowane-wizyty.html"
    def get(self, request):
        ja = lekarz_by_request(request)
        anulowane_wizyty = Wizyta.wizyty.filter_by_lekarz(ja, typ="ANUL").order_by('-dt_zak_anul')
        return render(request, self.template_name, {
            "anulowane_wizyty": anulowane_wizyty
        })


@method_decorator(login_required(login_url='/login'), name='dispatch')
@method_decorator(uprawniania_lekarz_wymagane, name='dispatch')
class LekarzRealizujWizyte(View):
    template_name = "przychodnia_app/lekarz/realizuj-wizyte.html"
    def get(self, request, wizyta_id):
        realizowana_wizyta = get_object_or_404(Wizyta, id=wizyta_id, status="REJ")
        bad_lab_w_ramach_wizyty = BadanieLaboratoryjne.badania.w_ramach_wizyty(
            realizowana_wizyta
        )
        bad_fiz_w_ramach_wizyty = BadanieFizykalne.badania.w_ramach_wizyty(
            realizowana_wizyta
        )
        context = {
            "wywiad_form": LekarzWywiadForm(instance=realizowana_wizyta),
            "realizowana_wizyta": realizowana_wizyta,
            "bad_lab_w_ramach_wizyty": bad_lab_w_ramach_wizyty,
            "bad_fiz_w_ramach_wizyty": bad_fiz_w_ramach_wizyty,
        }
        return render(request, self.template_name, context)

    def post(self, request, wizyta_id):
        wizyta_id = self.kwargs.get('wizyta_id')
        wywiad_action = request.POST.get('wywiad_action')
        realizowana_wizyta = get_object_or_404(Wizyta, id=wizyta_id, status="REJ")
        form = LekarzWywiadForm(request.POST, instance=realizowana_wizyta)

        if wywiad_action == "zapisz":
            form.save()
            messages.success(self.request, "Zapisano stan wizyty")
            return HttpResponseRedirect(reverse(
                "przychodnia_app:lekarz-realizuj-wizyte",
                kwargs={
                "wizyta_id": wizyta_id
                }
            ))

        if wywiad_action == "zatwierdz":
            form.save()
            realizowana_wizyta.status = "ZAK"
            realizowana_wizyta.dt_zak_anul = timezone.now()
            realizowana_wizyta.save()
            messages.success(self.request, "Wizyta została zakończona")
            return HttpResponseRedirect(reverse(
                "przychodnia_app:lekarz-moje-wizyty"
            ))

        messages.success(self.request, "Coś poszło nie tak. Skontaktuj się z administratorem")
        return HttpResponseRedirect(reverse(
            "przychodnia_app:lekarz-realizuj-wizyte",
            kwargs={
            "wizyta_id": wizyta_id
            }
        ))

@method_decorator(login_required(login_url='/login'), name='dispatch')
@method_decorator(uprawniania_lekarz_wymagane, name='dispatch')
class LekarzPrzegladajInneWizyty(ListView):
    template_name = "przychodnia_app/lekarz/przegladaj-inne-wizyty.html"
    paginate_by = 20
    model = Wizyta
    context_object_name = "inne_wizyty_pacjenta"
    allow_empty = True

    def get(self, request, *args, **kwargs):
        realizowana_wizyta = get_object_or_404(
            self.model, id=kwargs["wizyta_id"]
        )
        self.object_list = self.get_queryset(realizowana_wizyta)
        context = self.get_context_data()
        context = {
            "realizowana_wizyta": realizowana_wizyta,
            **context,
        }
        return self.render_to_response(context)

    def get_queryset(self, realizowana_wizyta):
        return self.model.wizyty.inne_wizyty_pacjenta(
            realizowana_wizyta
        ).order_by("-dt_rej")


class BadanieView():
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        wizyta_id = self.kwargs["wizyta_id"]
        realizowana_wizyta = get_object_or_404(
            Wizyta, id=wizyta_id, status="REJ"
        )
        context = {
            "realizowana_wizyta": realizowana_wizyta,
            **context,
        }
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        wizyta = get_object_or_404(
            Wizyta, id=self.kwargs.get("wizyta_id")
        )
        self.object.wizyta = wizyta
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


@method_decorator(login_required(login_url='/login'), name='dispatch')
@method_decorator(uprawniania_lekarz_wymagane, name='dispatch')
class LekarzZlecBadanieLaboratoryjne(BadanieView, CreateView):
    template_name = "przychodnia_app/lekarz/zlec-badanie-lab.html"
    form_class = ZlecBadanieLaboratoryjneForm

    def get_success_url(self):
        messages.success(self.request, "Badanie laboratoryjne dodane poprawnie")
        return reverse(
            "przychodnia_app:lekarz-realizuj-wizyte",
            kwargs={
                "wizyta_id": self.kwargs.get("wizyta_id")
            }
        )


@method_decorator(login_required(login_url='/login'), name='dispatch')
@method_decorator(uprawniania_lekarz_wymagane, name='dispatch')
class LekarzWykonajBadanieFizykalne(BadanieView, CreateView):
    template_name = "przychodnia_app/lekarz/wykonaj-badanie-fiz.html"
    form_class = WykonajBadanieFizykalneForm

    def get_success_url(self):
        messages.success(self.request, "Badanie fizykalne dodane poprawnie")
        return reverse(
            "przychodnia_app:lekarz-realizuj-wizyte",
            kwargs={
                "wizyta_id": self.kwargs.get("wizyta_id")
            }
        )

Przychodnia/przychodnia_app/views/views_przychodnia.py
from django.shortcuts import render, redirect, reverse
from django.utils import timezone
from django.views.generic.list import ListView
from przychodnia_pacjent.models import Pacjent
from django.shortcuts import get_object_or_404

from django.views.generic import View
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from common.access_decorators_mixins import (
    uprawnienia_wspolne_lekarz_rejestratorka
)
from django.views.generic.detail import DetailView
from przychodnia_wizyta.models import Wizyta
from laboratorium_app.models import BadanieLaboratoryjne
from przychodnia_bad_fiz.models import BadanieFizykalne


@method_decorator(login_required(login_url='/login'), name='dispatch')
@method_decorator(uprawnienia_wspolne_lekarz_rejestratorka, name='dispatch')
class PrzychodniaPacjentLista(ListView):
    template_name = "przychodnia_app/pacjent-lista.html"
    model = Pacjent
    context_object_name = 'pacjenci'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


@method_decorator(login_required(login_url='/login'), name='dispatch')
@method_decorator(uprawnienia_wspolne_lekarz_rejestratorka, name='dispatch')
class PrzychodniaWizytaDetail(DetailView):
    template_name = "przychodnia_app/wizyta-detail.html"
    context_object_name = "wizyta"
    model = Wizyta

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["badania_lab"] = BadanieLaboratoryjne.badania.w_ramach_wizyty(
            wizyta=kwargs.get('object')
        )
        context["badania_fiz"] = BadanieFizykalne.badania.w_ramach_wizyty(
            wizyta=kwargs.get('object')
        )
        return context


@method_decorator(login_required(login_url='/login'), name='dispatch')
@method_decorator(uprawnienia_wspolne_lekarz_rejestratorka, name='dispatch')
class PrzychodniaAnulujWizyte(View):
    template_name = "przychodnia_app/anuluj-wizyte.html"
    def get(self, request, wizyta_id):
        wizyta = get_object_or_404(Wizyta, pk=wizyta_id)
        return render(request, self.template_name, {"wizyta": wizyta})

    def post(self, request, wizyta_id):
        wizyta = get_object_or_404(Wizyta, pk=wizyta_id)
        wizyta.dt_zak_anul = timezone.now()
        wizyta.status = "ANUL"
        wizyta.save()
        return redirect(reverse("common:login"))

Przychodnia/przychodnia_app/templates/przychodnia_app/lekarz/moje-anulowane-wizyty.html
{% extends 'przychodnia_app/extend/base_przychodnia.html' %}
{% block title %}Lekarz{% endblock %}
{% block content %}


<h4><i class="fas fa-user-md"></i>&nbsp;Moje anulowane wizyty</h4>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Anulowano</th>
      <th scope="col">Pacjent</th>
      <th scope="col">Zarejestrowano</th>
      <th scope="col">Anulowano</th>
      <th scope="col">Akcje</th>
    </tr>
  </thead>
  <tbody>
    {% for wizyta in anulowane_wizyty %}
    <tr>
      <td>
        {{wizyta.dt_zak_anul}}
      </td>
      <td>
        {{wizyta.pacjent}}
      </td>
      <td>{{wizyta.dt_rej}}</td>
      <td>{{wizyta.dt_zak_anul}}</td>
      <td>
        {% include 'przychodnia_app/include/action_buttons_common.html' %}
      </td>
    </tr>
    {% empty %}
    <tr>
      <td colspan="4" class="text-center">
        -Brak-
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>


{% endblock %}

Przychodnia/przychodnia_app/templates/przychodnia_app/lekarz/moje-zakonczone-wizyty.html
{% extends 'przychodnia_app/extend/base_przychodnia.html' %}
{% block title %}Lekarz{% endblock %}
{% block content %}


<h4><i class="fas fa-user-md"></i>&nbsp;Moje zakończone wizyty</h4>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Zakończono</th>
      <th scope="col">Pacjent</th>
      <th scope="col">Umowiono na</th>
      <th scope="col">Akcje</th>
    </tr>
  </thead>
  <tbody>
    {% for wizyta in zakonczone_wizyty %}
    <tr>
      <td>
        {{wizyta.dt_zak_anul}}
      </td>
      <td>
        <a href="{% url 'przychodnia_app:przychodnia-pacjent-detail' pk=wizyta.pacjent.pk %}">
          {{wizyta.pacjent}}
        </a>
      </td>
      <td>{{wizyta.dt_rej}}</td>
      <td>
        {% include 'przychodnia_app/include/action_buttons_common.html' %}
      </td>
    </tr>
    {% empty %}
    <tr>
      <td colspan="4" class="text-center">
        -Brak-
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>


{% endblock %}

Przychodnia/przychodnia_app/templates/przychodnia_app/lekarz/realizuj-wizyte.html
{% extends 'przychodnia_app/extend/base_przychodnia.html' %}
{% block title %}Realizuj wizyte {{realizowana_wizyta.id}}{% endblock %}
{% block content %}
<style media="screen">
.nav-pills .nav-link {
  border-radius: 0;
}
</style>
{% with realizowana_wizyta as wizyta %}
<h4>
  <i class="fas fa-notes-medical"></i>
  &nbsp;Realizacja wizyty (ID={{wizyta.id}})
</h4>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-6">
      <div class="list-group flex-row mt-3">
        <a class="list-group-item border-0 p-0 pt-3 pb-3">
          <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1">Pacjent</h5>
          </div>
          <p class="mb-1">
            {{wizyta.pacjent.imie}} {{wizyta.pacjent.nazwisko}}
          </p>
          <small>
            {{wizyta.pacjent.pesel}}
          </small>
          <br>
          <small>
            {{wizyta.pacjent.adres}}
          </small>
        </a>
      </div>
      <p class="my-0">
        Umowiono na: <b>{{wizyta.dt_rej}}</b>
        przez <b>{{wizyta.rejestratorka}}</b>
      </p>
      {% include 'przychodnia_app/include/wizyta_status.html' with wizyta=wizyta %}
    </div>
    <div class="col-md-6">
      <a href="{% url 'przychodnia_app:lekarz-wykonaj-badanie-fiz' wizyta_id=wizyta.id %}" class="btn btn-block btn-success btn-sm">
        <i class="fas fa-stethoscope"></i>
        &nbsp;Wykonaj badanie fizykalne
      </a>
      <a href="{% url 'przychodnia_app:lekarz-zlec-badanie-lab' wizyta_id=wizyta.id %}" class="btn btn-block btn-primary btn-sm">
        <i class="fas fa-vial"></i>
        &nbsp;Zleć badanie laboratoryjne
      </a>
      <a href="{% url 'przychodnia_app:przegladaj-inne-wizyty-pacjenta' wizyta_id=wizyta.id %}" class="btn btn-block btn-secondary btn-sm">
        <i class="fas fa-notes-medical"></i>
        &nbsp;Przeglądaj inne wizyty pacjenta
      </a>
      <a href="{% url 'przychodnia_app:przychodnia-pacjent-badania' pk=wizyta.pacjent.pk %}" class="btn btn-block btn-secondary btn-sm">
        <i class="fas fa-notes-medical"></i>
        &nbsp;Przeglądaj badania pacjenta
      </a>
      <a class="btn btn-block btn-sm btn-danger" href="{% url 'przychodnia_app:przychodnia-anuluj-wizyte' wizyta_id=wizyta.pk %}" role="button">
        <i class="fas fa-ban"></i>
        &nbsp;Anuluj wizyte
      </a>
    </div>
  </div>
</div>

<hr>

<div class="container-fluid">
  <div class="row">
  {% if bad_fiz_w_ramach_wizyty or bad_lab_w_ramach_wizyty %}
  <div class="col-md-3">
    <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
      <a class="nav-link active" id="v-pills-home-tab" data-toggle="pill" href="#v-pills-home" role="tab" aria-controls="v-pills-home" aria-selected="true">
        <i class="fas fa-user-md"></i>&nbsp;
        Przeprowadź wywiad
      </a>
      {% if bad_fiz_w_ramach_wizyty %}
      <a class="nav-link" id="v-pills-messages-tab" data-toggle="pill" href="#v-pills-messages" role="tab" aria-controls="v-pills-messages" aria-selected="false">
        <i class="fas fa-stethoscope"></i>&nbsp;
        Badania fizykalne
      </a>
      {% endif %}
      {% if bad_lab_w_ramach_wizyty %}
      <a class="nav-link" id="v-pills-profile-tab" data-toggle="pill" href="#v-pills-profile" role="tab" aria-controls="v-pills-profile" aria-selected="false">
        <i class="fas fa-vial"></i>&nbsp;
        Badania laboratoryjne
      </a>
      {% endif %}
    </div>
  </div>
  {% endif %}
  {% if bad_fiz_w_ramach_wizyty or bad_lab_w_ramach_wizyty %}
  <div class="col-md-9">
  {% else %}
  <div class="col-md-12">
  {% endif %}
    <div class="tab-content" id="v-pills-tabContent">
      <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
        <form id="wywiad_form" action="." method="post">
          {% csrf_token %}
          {{wywiad_form}}
          <div class="pt-2"></div>
          <input type="hidden" id="wywiad_action" name="wywiad_action">
          <a onclick="decideAction('zatwierdz')" class="text-white btn btn-success">
            Zakończ wizytę
          </a>
          <a onclick="decideAction('zapisz')" class="text-white btn btn-primary">
            Zapisz stan wizyty
          </a>
        </form>
      </div>
      {% if bad_fiz_w_ramach_wizyty %}
      <div class="tab-pane fade" id="v-pills-messages" role="tabpanel" aria-labelledby="v-pills-messages-tab">
          <h5>
            <i class="fas fa-stethoscope"></i>
            &nbsp;Wykonane badania fizykalne w ramach tej wizyty
          </h5>
          {% include 'przychodnia_app/lekarz/badania/badanie_fiz_tabela.html' with badania_fizykalne=bad_fiz_w_ramach_wizyty %}
      </div>
      {% endif %}
      {% if bad_lab_w_ramach_wizyty %}
      <div class="tab-pane fade" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">
          <h5>
            <i class="fas fa-vial"></i>
            &nbsp;Badania laboratoryjne w ramach tej wizyty
          </h5>
          {% include 'przychodnia_app/lekarz/badania/badanie_lab_tabela.html' with badania_laboratorujne=bad_lab_w_ramach_wizyty %}
      </div>
      {% endif %}
    </div>
  </div>


</div>
</div>


<script type="text/javascript">
  function decideAction(act) {
    if(act === "zatwierdz") {
      q = confirm("Zakończone wizyty NIE mogą być modyfikowane. Czy na pewno chcesz zakończyć wizytę?");
      if(!q) {return;}
    }
    $('#wywiad_action').val(act);
    $('#wywiad_form').submit();
  }
</script>

{% endwith %}
{% endblock %}